Ext.define('Illi.model.Financeiro', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id'},
        {name: 'tipo'},
        {name: 'numero'},
        {name: 'data_emissao', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_emissao.date'},
        {name: 'data_referencia', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_referencia.date'},
        {name: 'data_vencimento', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_vencimento.date'},
        {name: 'data_baixa', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_baixa.date'},
        {name: 'data_prebaixa', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_prebaixa.date'},
        {name: 'data_exclusao', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_exclusao.date'},
        {name: 'data_arquivado', type: 'date', dateFormat: 'Y-m-d H:i:s', mapping: 'data_arquivado.date'},
        {name: 'valor_pago', type: 'float'},
        {name: 'valor_titulo', type: 'float'},
        {name: 'valor_multa', type: 'float'},
        {name: 'valor_juros', type: 'float'},
        {name: 'valor_desconto', type: 'float'},
        {name: 'valor_acrescimo', type: 'float'},
        {name: 'perc_acrescimo', type: 'int'},
        {name: 'perc_desconto', type: 'int'},
        {name: 'observacao'},
        {name: 'data'},
        {name: 'm.id', mapping: 'id_conta'},
        {name: 'c.id', type: 'int', mapping: 'id_conta'},
        {name: 'c.nome', mapping: 'c_nome'},
        {name: 'b.id', type: 'int', mapping: 'id_boleto'},
        {name: 'b.nossoNumero', mapping: 'nossonumero', type: 'string'},
        {name: 'p.id', type: 'int', mapping: 'id_pessoa'},
        {name: 'p.nome', mapping: 'p_nome'},
        {name: 'e.nome', mapping: 'e_nome'},
        {name: 'e.id', mapping: 'id_entidade'},
        {name: 'tp.nome', mapping: 'tp_nome'},
        {name: 'tp.id', mapping: 'tp_id'},
        {name: 'gp.grupo', mapping: 'grupoPessoa'},
        {name: 'gp.id', mapping: 'grupoPessoa'},
        {name: 'pz.descricao', mapping: 'pz_descricao'},
        {name: 'pz.id', mapping: 'id_prazo'},
        {name: 'nl.descricao', mapping: 'nl_descricao'},
        {name: 'nl.id', type: 'int', mapping: 'id_natureza_lancamento'},
        {name: 'saip'},
        {name: 'data_saip'},
        {name: 'id_fluxo', type: 'int'},
        {name: 'id_usuario', type: 'int'},
        {name: 'situacao'},
        {name: 'v.nome', mapping: 'v_nome'},
        {name: 'provisao'},
        {name: 'negociado'},
        {name: 'cnpj'},
        {name: 'cpf'},
        {name: 'conta'},
        {name: 'agencia'},
        {name: 'id_conta', type: 'int'},
        {name: 'movimenta_conta'}
    ]
});