Ext.define('Illi.model.produto.Produto', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id', mapping: 'id', type: 'int'},
        {name: 'gradex', mapping: 'gradex.nome'},
        {name: 'gradey', mapping: 'gradey.nome'},
        {name: 'pge.qtde', mapping: 'produtoGradeEstoque.qtde', type: 'float'},
        {name: 'pv.valor', mapping: 'precoVenda.valor', type: 'float'},
        {name: 'pc.valor', mapping: 'precoCusto.valor', type: 'float'},
        {name: 'p.id', mapping: 'produto.id'},
        {name: 'p.nome', mapping: 'produto.nome'},
        {name: 'nome', mapping: 'produto.nome'},
        {name: 'p.codigo', mapping: 'produto.codigo'},
        {name: 'codigo'},
        {name: 'p.descricao', mapping: 'produto.descricao'},
        {name: 'descricao', mapping: 'produto.descricao'},
        {name: 'p.observacao', mapping: 'produto.observacao'},
        {name: 'pg.estoque', mapping: 'estoque', type: 'int'},
        {name: 'p.situacao', mapping: 'produto.situacao'},
        {name: 'p.tipo', mapping: 'produto.tipo'},
        {name: 'pg.situacao', mapping: 'situacao'},
        {name: 'data', type: 'date', mapping: 'produto.data.date'},
        {name: 'u.id', type: 'int', mapping: 'produto.unidade.id'},
        {name: 'u.nome', mapping: 'produto.unidade.nome'},
        {name: 'g.id', type: 'int', mapping: 'produto.grupo.id'},
        {name: 'g.nome', mapping: 'produto.grupo.nome'},
        {name: 'ggx.id', type: 'int', mapping: 'produto.grupoGradex.id'},
        {name: 'ggx.nome', mapping: 'produto.grupoGradey.nome'},
        {name: 'ggy.id', type: 'int', mapping: 'produto.grupoGradey.id'},
        {name: 'ggy.nome', mapping: 'produto.grupoGradex.nome'},
        {name: 'c.id', type: 'int', mapping: 'produto.categoria.id'},
        {name: 'c.nome', mapping: 'produto.categoria.nome'},
        {name: 'm.id', type: 'int', mapping: 'produto.marca.id'},
        {name: 'm.nome', mapping: 'produto.marca.nome'},
        {name: 'complemento'}
    ]
});